[package]
name = "wapl"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", default-features = false, features = ["accesskit", "glow", "wayland", "web_screen_reader", "x11"] }
strum = { version = "0.26.3", features = ["derive"] }
